// File: sevensegdec_nexys.v
// Generated by MyHDL 0.11.52
// Date:    Tue Oct  6 18:50:28 2026 UTC


`timescale 1ns/10ps

module sevensegdec_nexys (
    bcd,
    sseg,
    bcdled,
    ssanodes,
    invert
);
// Envelope for running a demo in the Nexys4 DDR board for the Seven segment decoder

input [3:0] bcd;
output [6:0] sseg;
reg [6:0] sseg;
output [3:0] bcdled;
wire [3:0] bcdled;
output [7:0] ssanodes;
wire [7:0] ssanodes;
input invert;

reg [6:0] sevensegdec0_ssegout;


// LUT implementation: based on a decoder table
always @(bcd) begin: sevensegdec0_logic
    case (bcd)
        0: sevensegdec0_ssegout = 126;
        1: sevensegdec0_ssegout = 48;
        2: sevensegdec0_ssegout = 109;
        3: sevensegdec0_ssegout = 121;
        4: sevensegdec0_ssegout = 51;
        5: sevensegdec0_ssegout = 91;
        6: sevensegdec0_ssegout = 95;
        7: sevensegdec0_ssegout = 112;
        8: sevensegdec0_ssegout = 127;
        9: sevensegdec0_ssegout = 123;
        10: sevensegdec0_ssegout = 1;
        11: sevensegdec0_ssegout = 8;
        12: sevensegdec0_ssegout = 99;
        13: sevensegdec0_ssegout = 29;
        14: sevensegdec0_ssegout = 21;
        default: sevensegdec0_ssegout = 73;
    endcase
end

// Inverting process for output
always @(invert, sevensegdec0_ssegout) begin: sevensegdec0_invertproc
    if (invert) begin
        sseg = (~sevensegdec0_ssegout);
    end
    else begin
        sseg = sevensegdec0_ssegout;
    end
end

// Process to fill the LEDs for switches and display anodes

assign bcdled = bcd;
assign ssanodes = 8'hfe;

endmodule
